title: Scalable API Governance for Modern Engineering Organizations
description: Thoughts on how to organize and manage microservice APIs at scale.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
  

